### ISSUE TITLE
SSD boards causing disturbances

### ISSUE THREAD

**Issue by bengtssk** [Emile666/THD_Analyzer#6]
The the SSD modules are multiplexing the LED displays, it sends some voltage dips at the power rail. This voltages dips causes the both the frequency counter to malfunction and the residual distortion to increase. Using separate power supplies for 5 V supply and PCB1-3 boards does not help. The fast voltages spike are transmitted through the ground lead and/or coupled into the signal path anyway. This makes the whole instrument unusable.

My solution is to filter these voltage drop as close to the SSD boards as possible using a CL-filter. Using the circuit shown in the schematic almost completely removes these voltages spikes. Component values may not be so critical, these worked best for me.

The board is made so the SSD TM1637 module can be mounted directly to it, using some 5mm distances. I also chosen to mount two LED's at each boards. These are the indicating LED's for hz, khz, rms, peak-to-peak etc. I prefer to use standard 70mcd LED, which draw a bit more current than I want to load the micro controller with. So a transistor to drive each LED was also added.

![SSD_board_assembled](https://github.com/user-attachments/assets/94ebf19d-5128-4aeb-88bc-07ecba40588a)

[SSD-gerbers.zip](https://github.com/user-attachments/files/17446376/SSD-gerbers.zip)
[SSD_PSU_filtering-schematic.pdf](https://github.com/user-attachments/files/17446377/SSD_PSU_filtering-schematic.pdf)

**Comment by Emile666** [comment]
Excellent idea! It would definitely solve the problem with the voltage dips. Could I suggest to add the following:
- Have 3 LEDs instead of two, for Vp, Vpp and Vrms? I think the current TM1637 board only uses 4 of the 6 grid pins, so it would be relatively easy to add a couple of LEDs to it (e.g. to the grid 5 pin) and have it controlled by the software, instead of having the LED1, LED2 and LED3 pins. The interface would then be CLK, DIO, VCC and GND, just like it is now. The firmware (file tm1637.c, function tm1637_show_nr_dec_ex()) needs an update to control these LEDs, but that is not too difficult.
- Create one board and desolder both the SSD and the TM1637 from the existing board. The 3 LED solution can then easily be added.
- Add 4 x 3mm corner holes for screwing the PCB to a frontpanel. You probably need to move some components (C1) to the bottom layer in order to mount it.

This is probably the schematic for the existing TM1637 boards, it shows that the grid5 and grid6 are not connected yet:
![image](https://github.com/user-attachments/assets/248087cd-3ca2-4d9b-acc2-57b672bae718)

**Comment by bengtssk** [comment]
Very interesting idea, using the free grid of the LM1637 to control LED's. If your willing to to the software, I am happy to make a board for this. But it doesn't solve the problem with 3 LED's? One of the board should have 3 LEDs now, RMS, Vp, Vp-p. But the current uC baord doesn't support it anyway (?).

I intended to mount the board(s) using the same 3mm mounting hole that runs through the both boards. Just using some spacing screw and nuts etc...

**Comment by Emile666** [comment]
Solved in commit d910e729169950cfd8157a6c08a63e72a2f2400e.
